name: Build JS lib package
on:
  push:
    tags:
      - js/lib/v**
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: js/package-lock.json
          registry-url: https://registry.npmjs.org/
          scope: "@open-event-systems"
      - run: |
          npm ci
          npm -w lib run build
        working-directory: js

      - run: npm -w lib publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        working-directory: js
